// components/NavBar.vue
<template>
  <nav class="fixed w-full p-4 mb-3 bg-slate-100 shadow-md rounded-b-lg">
    <div class="flex items-center justify-between">
      <!-- Header logo -->
      <NuxtLink to="/">
        <Logo />
      </NuxtLink>

      <!-- Mobile toggle -->
      <div class="md:hidden">
        <button @click="drawer">
          <svg
            class="h-8 w-8 fill-current text-black"
            fill="none"
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path d="M4 6h16M4 12h16M4 18h16"></path>
          </svg>
        </button>
      </div>

      <!-- Navbar -->
      <div class="hidden md:block">
        <ul class="flex space-x-8 text-sm font-sans">
          <li v-for="item in items">
            <NuxtLink
              :to="item.route"
              :class="indicatorClassesNavBar(item.route)"
              >{{ item.title }}</NuxtLink
            >
          </li>
        </ul>
      </div>

      <!-- Dark Background Transition -->
      <transition
        enter-class="opacity-0"
        enter-active-class="ease-out transition-medium"
        enter-to-class="opacity-100"
        leave-class="opacity-100"
        leave-active-class="ease-out transition-medium"
        leave-to-class="opacity-0"
      >
        <div
          @keydown.esc="isOpen = false"
          v-show="isOpen"
          class="z-10 fixed inset-0 transition-opacity"
        >
          <div
            @click="isOpen = false"
            class="absolute inset-0 bg-black opacity-50"
            tabindex="0"
          ></div>
        </div>
      </transition>

      <!-- Drawer Menu -->
      <aside
        class="p-5 transform top-0 left-0 w-64 bg-slate-100 fixed h-full overflow-auto ease-in-out transition-all duration-300 z-30 text-gray-900"
        :class="isOpen ? 'translate-x-0' : '-translate-x-full'"
      >
        <div class="close">
          <button
            class="absolute top-0 right-0 mt-4 mr-4"
            @click="isOpen = false"
          >
            <svg
              class="w-6 h-6"
              fill="none"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path d="M6 18L18 6M6 6l12 12"></path>
            </svg>
          </button>
        </div>

        <span
          @click="isOpen = false"
          class="flex w-full items-center p-4 border-b"
        >
          <NuxtLink to="/">
            <Logo />
          </NuxtLink>
        </span>

        <ul class="divide-y font-sans">
          <li v-for="item in items">
            <NuxtLink
              v-bind:to="item.route"
              @click="isOpen = false"
              :class="`p-4 inline-block flex ${indicatorClassesDropdown(
                item.route
              )}`"
              >{{ item.title }}</NuxtLink
            >
          </li>
        </ul>
      </aside>
    </div>
  </nav>
  <div class="py-8"></div>
</template>

<script setup lang="ts">
import { RouteLocationNormalizedLoaded, useRoute } from "vue-router";
const currentRoute: RouteLocationNormalizedLoaded = useRoute();
function indicatorClassesNavBar(route: String): String {
  if (route == currentRoute.fullPath)
    return "active border-b-2 border-blue-500 pb-1";
  else return "";
}
function indicatorClassesDropdown(route: String): String {
  if (route == currentRoute.fullPath)
    return "text-slate-500 font-extrabold bg-slate-200";
  else return "";
}
</script>

<script lang="ts">
export default {
  data() {
    let items: { route: String; title: String }[] = [
      { route: "/", title: "Home" },
      { route: "/impressum", title: "Impressum" },
      { route: "/data-protection", title: "Data Protection" },
    ];
    return {
      isOpen: false,
      items: items,
    };
  },
  methods: {
    drawer() {
      this.isOpen = !this.isOpen;
    },
  },
  watch: {
    isOpen: {
      immediate: true,
      handler(isOpen) {
        if (process.client) {
          if (isOpen) document.body.style.setProperty("overflow", "hidden");
          else document.body.style.removeProperty("overflow");
        }
      },
    },
  },
  mounted() {
    document.addEventListener("keydown", (e) => {
      if (e.keyCode == 27 && this.isOpen) this.isOpen = false;
    });
  },
};
</script>

// personal_site/components/navbar.tsx
"use client";

import * as React from "react"
import Logo from "./logo"
import { useState } from "react"
import Link from "next/link";

const NavBar = ({ currentRoute }: { currentRoute: string }) => {
  const drawer = () => {
    setDrawerState(!isOpen);
  }
  const [isOpen, setDrawerState] = useState(false);
  const currentRouteIndicator = (route: String) => {
    if (route == currentRoute)
      return "bg-navbar-indicator"
    else return ""
  }
  let items: { route: string; title: string }[] = [
    { route: "/", title: "Home" }
  ]
  return (
    <div>
      <nav className="fixed w-full p-4 mb-3 bg-navbar-bg shadow-md rounded-b-lg z-50">
        <div className="flex items-center justify-between">
          <Link href="/">
            <Logo />
          </Link>
          {/* Mobile toggle */}
          <div className="md:hidden">
            <button type="button" onClick={drawer}>
              <svg
                className="h-8 w-8 fill-current text-black"
                fill="none"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="2"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path d="M4 6h16M4 12h16M4 18h16"></path>
              </svg>
            </button>
          </div>
          {/* Navbar */}
          <div className="hidden md:block">
            <ul className="flex space-x-8 text-sm font-sans">
              {items.map(item => (
                <li key={item.route}>
                  <Link
                    href={item.route}
                  >
                    {item.title}
                  </Link>
                  <div className={`h-0.5 rounded ${currentRouteIndicator(item.route)}`}></div>
                </li>
              ))}
            </ul>
          </div>
          {/* Dark background transition */}


          {/* Drawer menu */}
          <aside
            className={
              "p-5 transform top-0 left-0 w-64 bg-navbar-sidebarbg fixed h-full overflow-auto ease-in-out transition-all duration-300 z-50 text-gray-900 " +
              (isOpen ? "translate-x-0" : "-translate-x-full")
            }
          >
            <div className="close">
              <button
                className="absolute top-0 right-0 mt-4 mr-4"
                onClick={() => {
                  setDrawerState(false)
                }}
              >
                <svg
                  className="w-6 h-6"
                  fill="none"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth="2"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path d="M6 18L18 6M6 6l12 12"></path>
                </svg>
              </button>
            </div>

            <span
              onClick={() => {
                setDrawerState(false);
              }}
              className="flex w-full items-center p-4 border-b"
            >
              <Link href="/">
                <Logo />
              </Link>
            </span>
            <ul className="divide-y font-sans">
              {items.map(item => (
                <li key={item.route}>
                  <Link
                    href={item.route}
                    className={
                      "p-4 inline-block flex"
                    }
                    onClick={() => {
                      setDrawerState(false);
                    }}
                  >
                    {item.title}
                  </Link>
                  <div className={`h-0.5 rounded ${currentRouteIndicator(item.route)}`}></div>
                </li>
              ))}
            </ul>
          </aside>
        </div>
      </nav>
      <div className="py-8"></div>
    </div>
  )
}

export default NavBar
